[package]
name = "documentdb_gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
bson = "2.7.0"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.9"
bitflags = "1.1.0"
async-recursion = "1.0.5"
serde_json = { version = "1.0.107", features = ["arbitrary_precision"] }
rand = "0.8.5"
deadpool-postgres = "0.11.0"
regex = "1.10.2"
once_cell = "1.18.0"
hex = "0.4.3"
openssl = "0.10.73"
tokio-openssl = "0.6.5"
either = "1.13.0"
socket2 = "0.5.7"
documentdb_macros = { path = "./documentdb_macros" }
async-trait = "0.1.88"
dyn-clone = "1.0.19"
whoami = "1.6.0"
arc-swap = "1.7.1"
simple_logger = { version = "4.2.0", default-features = false, features = [
    "timestamps",
] }
# do not add any *_max_level_info features unless the max_level wants to be applied to the whole project
log = { version = "0.4.20", features = ["kv"] }
tokio-postgres = { version = "0.7.10", features = [
    "with-serde_json-1",
    "array-impls",
] }
serde = { version = "1.0.125", features = ["derive", "rc"] }
uuid = { version = "1.12.1", features = ["v4"] }

[dev-dependencies]
mongodb = { version = "3.2.0", default-features = false, features = [
    "dns-resolver",
    "openssl-tls",
    "compat-3-0-0",
] }

[lints.clippy]
complexity = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }

[profile.release-with-symbols]
inherits = "release"
# Generates the minimal amount of debug info for backtraces with filename/line number info, but not anything else
debug = "line-tables-only"
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true
